FINANCIAL_RULES = [
    {
        "id": "RULE-01",
        "name": "Cash-flow deficit",
        "category": "Financial health",
        "description": "Expenses exceed income, which can indicate recurring cash-flow stress.",
        "required_inputs": ["total_income", "total_expenses"],
        "conditions": "total_expenses > total_income",
        "thresholds": {"warning_if": "expenses > income"},
        "result": "A recurring deficit may reduce savings and increase dependence on debt or credit.",
        "severity": "high",
        "evidence": "Monthly inflows are lower than outflows in the uploaded data.",
        "recommended_action": "Review spending priorities and avoid new debt until the gap is reduced.",
        "source": "Internal financial-health rule set",
        "rule_version": "v1.0",
    },
    {
        "id": "RULE-02",
        "name": "Debt burden check",
        "category": "Debt management",
        "description": "Large recurring loan payments relative to income can create debt stress.",
        "required_inputs": ["total_income", "loan_and_emi_amount"],
        "conditions": "loan_and_emi_amount / total_income >= 0.35",
        "thresholds": {"warning_if": "EMI or loan payments exceed 35% of income"},
        "result": "EMI obligations consume a large share of income and can limit resilience.",
        "severity": "high",
        "evidence": "Recurring loan and EMI-related transactions are a significant share of total income.",
        "recommended_action": "Reassess affordability and consider restructuring, repayment planning, or expert advice.",
        "source": "Internal debt-risk rule set",
        "rule_version": "v1.0",
    },
    {
        "id": "RULE-03",
        "name": "Savings rate caution",
        "category": "Savings resilience",
        "description": "A weak savings rate can leave the household without a financial buffer.",
        "required_inputs": ["total_income", "net_savings"],
        "conditions": "net_savings / total_income < 0.10",
        "thresholds": {"warning_if": "savings rate below 10%"},
        "result": "Low savings reduce the ability to handle emergencies or price shocks.",
        "severity": "moderate",
        "evidence": "A small surplus or deficit indicates limited cash buffers.",
        "recommended_action": "Increase monthly surplus and build a small emergency reserve before taking more risk.",
        "source": "Internal resilience rule set",
        "rule_version": "v1.0",
    },
]
