EXPERT_KNOWLEDGE = [
    {
        "id": "EXP-01",
        "expert_name": "Reserve Bank of India Financial Education",
        "source_organization": "Reserve Bank of India",
        "topic": "Emergency fund",
        "recommendation": "Maintain an emergency reserve to cover essential expenses for a meaningful period and avoid relying on fresh borrowing for routine shocks.",
        "source_url": "https://www.rbi.org.in/",
        "publication_date": "current-public-principle",
        "geographic_context": "India",
        "applicability": "general personal finance",
        "reliability_status": "verified institutional source",
    },
    {
        "id": "EXP-02",
        "expert_name": "World Bank / OECD personal finance guidance",
        "source_organization": "World Bank / OECD",
        "topic": "Debt and cash-flow management",
        "recommendation": "Avoid using high-cost borrowing to cover recurring expenses or to compensate for an ongoing income shortfall.",
        "source_url": "https://www.worldbank.org/",
        "publication_date": "current-public-principle",
        "geographic_context": "global",
        "applicability": "debt stress and household cash-flow guidance",
        "reliability_status": "verified institutional source",
    },
    {
        "id": "EXP-03",
        "expert_name": "SEBI investor education",
        "source_organization": "SEBI",
        "topic": "Diversification and risk",
        "recommendation": "Diversification across asset classes and a clear understanding of risk are generally preferred over concentration in a single volatile asset class.",
        "source_url": "https://www.sebi.gov.in/",
        "publication_date": "current-public-principle",
        "geographic_context": "India",
        "applicability": "investment allocation and risk management",
        "reliability_status": "verified institutional source",
    },
    {
        "id": "EXP-04",
        "expert_name": "Consumer financial resilience guidance",
        "source_organization": "OECD / financial resilience literature",
        "topic": "Financial resilience",
        "recommendation": "A household with limited surplus, rising debt, and weak liquidity faces increased risk if additional borrowing is taken without a repayment plan.",
        "source_url": "https://www.oecd.org/",
        "publication_date": "current-public-principle",
        "geographic_context": "global",
        "applicability": "financial distress and solvency review",
        "reliability_status": "verified institutional source",
    },
]
